# Default values
image:
  repository: docker.io/fhopfensperger/simple-go-app
serviceAccountName: pipeline

git:
  repoUrl: https://github.com/fhopfensperger/simple-go-app.git
  
cicd:
  repoUrl: https://github.com/fhopfensperger/gitops-cicd.git
  filepath: ./charts/simple-go-app/values.yaml

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: hopfi.selfhost.co
      paths:
        - /tekton-el/simple-go-app
  tls: 
   - secretName: hopfi-selfhost-co-tls
     hosts:
       - hopfi.selfhost.co