###################################################################################################
# {{ .Release.Name }} Trigger
###################################################################################################
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ include "microservice.fullname" . }}
spec:
  serviceAccountName: {{ .Values.serviceAccountName }}
  triggers:
    - triggerRef: {{ include "microservice.fullname" . }}