autoscaling:
  enabled: true
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
env:
- name: QUARKUS_JAEGER_SERVICE_NAME
  value: '{{ .Release.Name }}.{{ .Release.Namespace }}'
image:
  pullPolicy: Always
  repository: docker.io/fhopfensperger/simple-go-app:8e8b70b74345a8262ab776d447d888c96cee8a58
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  enabled: true
  hosts:
  - host: hopfi.selfhost.co
    paths:
    - /hello
  tls:
  - hosts:
    - hopfi.selfhost.co
    secretName: hopfi-selfhost-co-tls
nameOverride: simple-go-app
podAnnotations: {}
podSecurityContext: {}
reason: unknown
replicaCount: 1
resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 100Mi
securityContext: {}
service:
  port: 8080
  type: ClusterIP
