# Default values
nameOverride: simple-go-app
replicaCount: 1
image:
  repository: docker.io/fhopfensperger/simple-go-app:latest
  pullPolicy: Always
reason: unknown

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 100m
    memory: 100Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: hopfi.selfhost.co
      paths:
        - /hello
  tls: 
   - secretName: hopfi-selfhost-co-tls
     hosts:
       - hopfi.selfhost.co

env:
  - name: QUARKUS_JAEGER_SERVICE_NAME
    value: "{{ .Release.Name }}.{{ .Release.Namespace }}"