apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-push-image
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: git-url
      type: string
      description: url of the git repo for the code of deployment
    - name: git-revision
      type: string
      description: revision to be used from repo of the code for deployment
      default: "master"
    - name: IMAGE
      type: string
      description: image to be build from the code
    - name: TAG
      type: string
      description: image tag to be build from the code
    - name: git-cicd-url
      type: string
      description: url of the git repo for the deployment
    - name: version-file-path
      type: string
      description: local file path for the deployment or values
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: Task
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: $(params.git-revision)

    - name: build-image
      taskRef:
        name: buildah
        kind: Task
      params:
        - name: TLSVERIFY
          value: "false"
        - name: IMAGE
          value: $(params.IMAGE)
        - name: TAG
          value: $(params.TAG)
        - name: FORMAT
          value: "docker"
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - fetch-repository

    - name: update-stage-deployment-image
      taskRef:
        name: image-updater
      runAfter:
        - build-image
      params:
        - name: driver
          value: "github"
        - name: file-path
          value: $(params.version-file-path)
        - name: image-repo
          value: $(params.IMAGE)
        - name: new-image-url
          value: "$(params.IMAGE):$(params.TAG)" 
        - name: source-branch
          value: "main"
        - name: source-repo
          value: $(params.git-cicd-url)
        - name: update-key
          value: "image.tag"
        - name: insecure
          value: "true"
        - name: branch-generate-name
          value: ""