kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-role
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "create", "update", "patch", "list", "watch"]
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners"]
  verbs: ["get", "create", "update", "patch", "list", "watch"]
- apiGroups: ["triggers.tekton.dev"]
  resources: ["triggers"]
  verbs: ["get", "create", "update", "patch", "list", "watch"]
- apiGroups: ["triggers.tekton.dev"]
  resources: ["triggerbindings"]
  verbs: ["get", "create", "update", "patch", "list", "watch"]
- apiGroups: ["triggers.tekton.dev"]
  resources: ["triggertemplates"]
  verbs: ["get", "create", "update", "patch", "list", "watch"]
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns"]
  verbs: ["get", "create", "update", "patch", "list", "watch"]
- apiGroups: [""]
  resources: ["users", "groups", "serviceaccounts"]
  verbs: ["impersonate"]